import { type TranslationKey, type TranslationParams, t } from './i18n';

// SSH 协议状态事件到 i18n 词条的静态映射表
const SSH_EVENT_KEYS: Record<string, TranslationKey> = {
  jump_hop_connecting: 'terminal.status.jumpHopConnecting',
  jump_target_connecting: 'terminal.status.jumpTargetConnecting',
  version_exchange: 'terminal.status.versionExchange',
  version_ready: 'terminal.status.versionReady',
  auth_public_key: 'terminal.status.authPublicKey',
  auth_service_accepted: 'terminal.status.authServiceAccepted',
  auth_interactive_required: 'terminal.status.authInteractiveRequired',
  auth_interactive_cancelled: 'terminal.status.authInteractiveCancelled',
  auth_interactive_protocol_error: 'terminal.status.authInteractiveProtocolError',
  auth_interactive_limit: 'terminal.status.authInteractiveLimit',
  auth_interactive_client_unavailable: 'terminal.status.authInteractiveClientUnavailable',
  auth_interactive_timeout: 'terminal.status.authInteractiveTimeout',
  auth_interactive_stale: 'terminal.status.authInteractiveStale',
  auth_interactive_invalid_response: 'terminal.status.authInteractiveInvalidResponse',
  auth_interactive_send_failed: 'terminal.status.authInteractiveSendFailed',
  auth_interactive_failed: 'terminal.status.authInteractiveFailed',
  auth_password_change_required: 'terminal.status.authPasswordChangeRequired',
  auth_protocol_error: 'terminal.status.authProtocolError',
  auth_success: 'terminal.status.authSuccess',
  auth_failed: 'terminal.status.authFailed',
  shell_ready: 'terminal.status.shellReady',
  session_ended: 'terminal.status.sessionEnded',
  remote_closed: 'terminal.status.remoteClosed',
  keepalive_timeout: 'terminal.status.keepaliveTimeout',
  idle_timeout: 'terminal.status.idleTimeout',
  session_idle_timeout: 'terminal.status.sessionIdleTimeout',
  session_idle_warning: 'terminal.status.sessionIdleWarning',
  input_backlog_closed: 'terminal.status.inputBacklogClosed',
  packet_error: 'terminal.status.packetError',
  algorithm_error: 'terminal.status.algorithmError',
  service_error: 'terminal.status.serviceError',
  host_key_accepted: 'terminal.status.hostKeyAccepted',
  host_key_fingerprint_matched_unverified: 'terminal.status.hostKeyFingerprintMatchedUnverified',
  host_key_first_seen: 'terminal.status.hostKeyFirstSeen',
  host_key_not_saved: 'terminal.status.hostKeyNotSaved',
  host_key_changed: 'terminal.status.hostKeyChanged',
  host_key_known: 'terminal.status.hostKeyKnown',
  host_key_actual: 'terminal.status.hostKeyActual',
  host_key_trust_instruction: 'terminal.status.hostKeyTrustInstruction',
  host_key_unverified_instruction: 'terminal.status.hostKeyUnverifiedInstruction',
  host_key_unsupported: 'terminal.status.hostKeyUnsupported',
  host_key_verify_skipped: 'terminal.status.hostKeyVerifySkipped',
  host_key_signature_blocked: 'terminal.status.hostKeySignatureBlocked',
  host_key_signature_risk: 'terminal.status.hostKeySignatureRisk',
  host_key_signature_error: 'terminal.status.hostKeySignatureError',
  channel_rejected: 'terminal.status.channelRejected',
  pty_shell_rejected: 'terminal.status.ptyShellRejected',
  send_data_failed: 'terminal.status.sendDataFailed',
  resize_failed: 'terminal.status.resizeFailed',
  share_session_expired: 'terminal.status.shareSessionExpired',
  share_expiring_warning: 'terminal.status.shareExpiringWarning',
  share_audit_unavailable: 'terminal.status.shareAuditUnavailable',
};

export function localizedSSHMessage(
  message: string,
  event?: string,
  params: TranslationParams = {}
): string {
  const key = event ? SSH_EVENT_KEYS[event] : undefined;
  return key ? t(key, params) : message;
}
