name: Deploy to GitHub Pages

on:
  push:
    branches: [test, main]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository_owner == 'newbietan'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # actions/checkout@v4.4.0
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Pages
        # actions/configure-pages@v4
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d

      - name: Upload artifact
        # actions/upload-pages-artifact@v3
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: "docs"

      - name: Deploy to GitHub Pages
        id: deployment
        # actions/deploy-pages@v4
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
